version: 2.1.0.{build}
os: Visual Studio 2017
configuration: Debug
platform: Any CPU

branches:
  only:
  - master

skip_tags: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: XvmOROcqgidalZg23H16UjDbAxIMkpuVXwKKPEp0bq3W5J2av35X1BsZvClM25JX

install:
  - cmd: git submodule update --init --recursive
  - cmd: nuget restore submodules\MimeKit\MimeKit.Net45.sln
  - cmd: nuget restore MailKit.Net45.sln

build:
  project: MailKit.Net45.sln
  verbosity: minimal

test_script: 
  - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[MailKit]* -[UnitTests]* -[submodules]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/framework:net-4.5 /noshadow /domain:single UnitTests\bin\Debug\UnitTests.dll" -output:opencover.xml
  - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover opencover.xml -r %COVERALLS_REPO_TOKEN%
